### PR TITLE
Cent os7 update

### PR DESCRIPTION
**Pull request by Gregg140**
Addition of stdout buffer flush and a change of the sftp from a forked process to an inline call.

These two changes returns the screen output to an orderly listing.

### CODE REVIEW

**Comment by Gregg140** [comment]
Please review - I'd like to get this merged and uploaded before next week's load

thanks!

**Comment by cegrant** [comment]
What happens if it can't connect to lucky, if something's wrong with the network or lucky is down?  You don't want LR to continue if there's isn't a backstop file, so does it die later on?

**Comment by Gregg140** [comment]
In an earlier email to acisdude, I described the use of the -nolucky 
switch whenever the backstop file is unavailable on lucky for any reason.

**Comment by cegrant** [comment]
I don't mean when lucky is known to be down.  I mean if the on-duty person thinks everything is OK, starts up a normal LR run, but unbeknownst to them, lucky is down.  What happens then.

**Comment by Gregg140** [comment]
Here is the pertinent section of the acisdude email:

2) But now if you don't want the GET command to be issued, you have to use the long-in-existence lr switch called:

nolucky


This will allow you to copy in a backstop file and avoids the sftp

**Comment by Gregg140** [comment]
> I mean if the on-duty person thinks everything is OK, starts up a normal LR run, but unbeknownst to them, lucky is down. What happens then.

Ah I need to add a "die" to the code in case the sftp status returns as failed....hang on.

**Comment by Gregg140** [comment]
Ok I've captured the status of the sftp and tested the value. If lucky does not exist, or it exists but the load week directory does not exist (e.g. NOV0518), or if the load week directory DOES exist but is empty  (e.g. NOV1218), or if you flub the login, then lr will exit gracefully.

**Comment by cegrant** [comment]
I'm happy.  Thanks!

**Comment by jzuhone** [comment]
Looks good!

**Comment by richardjedgar** [comment]
Looks good to me!

**Pull request merged**
