### PR TITLE
Latest operational LR programs which reside in the ...LoadReview/scri…

### PR DESCRIPTION
**Pull request by Gregg140**
This pull request is an update to the LR repo which consists of an updated lr and all programs used by lr which reside in the /data/acis/LoadReview/script directory.

These are not all the files used by LR - for example the models live in a different directory as well as programs such as the bright-sources software.

### CODE REVIEW

**Comment by Gregg140** [comment]
These two pull requests add a number of files to the repo.

There is one change...lr.

That's the only piece of code that requires a review for changes.

Please have a look and then someone do the merge if satisfactory

**Comment by Gregg140** [comment]
These two commits and pull request add several files to the LR erpo.

Only "lr" itself has a code change that needs to be reviewed. Please review and merge if satisfactory.

thanks

**Comment by Gregg140** [comment]
re-opened

**Review by richardjedgar — APPROVED** [review]
The LR changes look good to me. The other changes are just more files being checked into the git system.

**Review by jzuhone — APPROVED** [review]

**Pull request merged**
