### PR TITLE
Minor change to lr made due to a premature merge

### PR DESCRIPTION
**Pull request by Gregg140**
Please look over the changes, approve them if approvable.

But do not merge. ;)

Thanks

### CODE REVIEW

**Review by cegrant — APPROVED** [review]
Looks OK to me

**Review by richardjedgar — APPROVED** [review]
I'm fine with this.

**Comment by jzuhone** [comment]
Wait, this is just an extra comment line?

**Comment by jzuhone** [comment]
If this is just here to be a placeholder for the one we accidentally merged, we probably shouldn't do that. If you link to the PR in your description sent to mpweekly someone will catch it and probably complain. It's just as well to say we accidentally merged the change but haven't installed the changes yet.

**Comment by Gregg140** [comment]
Yeah that's all it was.

I was going to point them to PR 16 in the release notes so that they can 
see the actual changes.

Then I was going to explain during the LR telecon that it was 
accidentally merged.

Seems like they could complain either way. But if it's better to not 
have the placeholder then I can get rid of it.

**Comment by jzuhone** [comment]
I think we should probably just cancel this PR then.

**Comment by Gregg140** [comment]
ok I'll cancel it

**Pull request closed without merging**
