### PR TITLE
Fixed erroneous reports of the 1 hour, all FEPs off rule

### PR DESCRIPTION
**Pull request by Gregg140**
Tested against all load types (e.g. Normal, TOO, SCS-107, Full Stop), and all loads where the
error was flagged erroneously.

### CODE REVIEW

**Comment by jeanconn** [comment]
For this conversation PR, I'm happy to help review, but I could use a description about how the bug happened (I don't see a description of *why* it was firing erroneously) and how the changes address that issue.

**Comment by Gregg140** [comment]
Hi Jeam,

The basic problem was that the state code that updates the state had to run the state update rules prior to the next round of Command Checking rules.  Without updating the state it was using an old power command time stamp value and erroneously reporting a violation of the 1 hour rule between WSPOW00000 and subsequent power commands.    (line 238 of Check_Power_Commands.py inthe diffs).  The comment there is:

# June 2019 change - first run the state rules...

**Comment by Gregg140** [comment]
Jean - also the PR contains the Release Notes which may help you to understand what's been fixed

**Review by jzuhone — APPROVED** [review]

**Review by jazan12 — APPROVED** [review]
Did my best to assess on lookthrough alone and saw no issues.

**Pull request merged**
